# Generated by Django 4.2.1 on 2023-05-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_app', '0004_customer_farmer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='FoodGrains',
        ),
    ]
