# Generated by Django 4.2.1 on 2023-05-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_app', '0006_foodgrains_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgrains',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
