# Generated by Django 4.2.1 on 2023-05-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_app', '0007_foodgrains_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgrains',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
