# Generated by Django 4.2.1 on 2023-05-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_app', '0010_alter_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='unordered', max_length=100),
        ),
    ]
